# docker-compose.yml
version: "3"
services:
  server:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    build: ./postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
